In [1]:
#import the numpy libray and its linear algebra sublibrary
import numpy as np
from numpy import linalg as la
eps=1e-8

In [2]:
#examples
A=np.array([[1,2,3],[4,5,6],[2,8,2]])

In [3]:
#computing the right and left eigenvalues and vectors
# @ refers to the simple contracted product and .T provides the transpose
# R: matrix whose columns are right eigenvectors. 
# L: matrix whose rows are left eigenvectors. 
# LAM: diagonal matrix whose entries are the eigenvalues
lamb1, R = la.eig(A)
lamb2, L = la.eig(A.T) 
L=L.T
print("R = \n",R)
print("L = \n",L)
LAM = np.diag(lamb1)
print("[lambda] = \n",LAM)

R = 
 [[-3.02079270e-01 -8.32050294e-01 -4.08248290e-01]
 [-7.14005547e-01  2.07143878e-16 -4.08248290e-01]
 [-6.31620292e-01  5.54700196e-01  8.16496581e-01]]
L = 
 [[-0.37139068 -0.74278135 -0.55708601]
 [-0.84515425  0.50709255 -0.16903085]
 [ 0.39801488 -0.69652603  0.59702231]]
[lambda] = 
 [[12.  0.  0.]
 [ 0. -1.  0.]
 [ 0.  0. -3.]]


In [6]:
#check that w is made by the right eigenvectors. We compute C = A.R-R.LAM. We replace small values by 0. 
 
# We check that this matrix is zero
C=A@R-R@LAM
C[abs(C)<eps]=0
print(C)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [8]:
#We do the same with thee left eigenvectors and check that C=L.A-L.LAM is zero.
C=L@A - LAM @L
C[abs(C)<eps]=0
print(C)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [9]:
#Check that the product L.R gives a diagonal matrix
lr=L@R
lr[lr<eps]=0
print(lr)


[[0.99440626 0.         0.        ]
 [0.         0.6094494  0.        ]
 [0.         0.         0.60933335]]


In [57]:
#left and right eigenvectors are perpendicular when not associated with the same eigenvalue
w1 = R[:,0] # First column is the first right eigenvector
w2 = R[:,1]
w3 = R[:,2]
 
v1 = L[0,:] # First row is the first left eigenvector
v2 = L[1,:]
v3 = L[2,:]

# v_1.A-lambda_1v_1 = 0 ?
result=v1@A-lamb[0]*v1
result[result<eps]=0

print("v_1.A-lambda_1*v_1 = ",result)
# v_1 and w_1 normal?
vw11=v1@w1; 
vw12=v1@w3; 
print("v_1.w_1 = ",vw11)
print("v_1.w_2 = ",vw12)

v_1.A-lambda_1*v_1 =  [0. 0. 0.]
v_1.w_1 =  0.9944062617398504
v_1.w_2 =  0.0
